const PRODUCTS = [
    // TEA
    {
        id: "t1",
        name: "Classic Cutting Chai",
        category: "Tea",
        price: 20,
        rating: 4.8,
        reviewsCount: 320,
        description: "Authentic Indian street-style kadak chai brewed with fresh whole milk and CTC tea leaves.",
        ingredients: ["Whole Milk", "CTC Tea Leaves", "Sugar", "Water"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "t2",
        name: "Special Masala Tea",
        category: "Tea",
        price: 30,
        rating: 4.9,
        reviewsCount: 450,
        description: "Aromatic black tea simmered with cardamom, cinnamon, cloves, and ginger.",
        ingredients: ["Cardamom", "Cinnamon", "Cloves", "Ginger", "Milk", "Tea Leaves"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "t3",
        name: "Fresh Ginger Elaichi Chai",
        category: "Tea",
        price: 30,
        rating: 4.7,
        reviewsCount: 210,
        description: "Rejuvenating milk tea infused with crushed fresh ginger root and green cardamom.",
        ingredients: ["Fresh Ginger", "Green Cardamom", "Milk", "Assam Tea"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "t4",
        name: "Honey Lemon Green Tea",
        category: "Tea",
        price: 35,
        rating: 4.6,
        reviewsCount: 180,
        description: "Light Darjeeling green tea paired with raw organic honey and fresh squeezed lemon.",
        ingredients: ["Green Tea Leaves", "Raw Honey", "Lemon Slices", "Filtered Water"],
        isVeg: true,
        isVegan: true,
        isEggless: true,
        badge: "New",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80"
    },

    // COFFEE
    {
        id: "c1",
        name: "South Indian Filter Coffee",
        category: "Coffee",
        price: 30,
        rating: 4.9,
        reviewsCount: 520,
        description: "Traditional frothy brass decoction coffee prepared with chicory blend and frothy hot milk.",
        ingredients: ["Coffee Decoction", "Chicory", "Hot Milk", "Sugar"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "c2",
        name: "Classic Cappuccino",
        category: "Coffee",
        price: 80,
        rating: 4.8,
        reviewsCount: 290,
        description: "Rich double shot espresso topped with steamed milk and thick micro-foam dusted with cocoa powder.",
        ingredients: ["Arabica Espresso", "Steamed Milk", "Milk Foam", "Cocoa Powder"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "c3",
        name: "Creamy Café Latte",
        category: "Coffee",
        price: 90,
        rating: 4.7,
        reviewsCount: 310,
        description: "Smooth espresso poured over velvety steamed milk with subtle latte art.",
        ingredients: ["Espresso", "Steamed Whole Milk", "Micro-foam"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "c4",
        name: "Dark Mocha Delight",
        category: "Coffee",
        price: 110,
        rating: 4.9,
        reviewsCount: 195,
        description: "Espresso combined with rich Belgian chocolate sauce, hot milk, and whipped cream.",
        ingredients: ["Espresso", "Dark Chocolate Sauce", "Steamed Milk", "Whipped Cream"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1607260550778-ea9d295b44e2?auto=format&fit=crop&w=600&q=80"
    },

    // COLD BEVERAGES
    {
        id: "cb1",
        name: "Signature Iced Cold Coffee",
        category: "Cold Beverages",
        price: 100,
        rating: 4.9,
        reviewsCount: 640,
        description: "Chilled espresso blended with dark cocoa, vanilla ice cream, and ice cubes.",
        ingredients: ["Espresso", "Vanilla Ice Cream", "Chilled Milk", "Chocolate Syrup"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "cb2",
        name: "Belgium Chocolate Shake",
        category: "Cold Beverages",
        price: 120,
        rating: 4.8,
        reviewsCount: 280,
        description: "Thick milk shake crafted with 70% dark Belgian chocolate ganache and chocolate scoop.",
        ingredients: ["Dark Belgian Chocolate", "Milk", "Chocolate Ice Cream", "Choco Chips"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "cb3",
        name: "Fresh Mint Lime Soda",
        category: "Cold Beverages",
        price: 60,
        rating: 4.6,
        reviewsCount: 150,
        description: "Sparkling soda loaded with fresh crushed mint leaves, lime juice, and black salt.",
        ingredients: ["Fresh Lime", "Mint Leaves", "Sparkling Water", "Rock Salt", "Sugar Syrup"],
        isVeg: true,
        isVegan: true,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "cb4",
        name: "Peach & Passion Iced Tea",
        category: "Cold Beverages",
        price: 70,
        rating: 4.7,
        reviewsCount: 190,
        description: "Brewed black tea chilled over crushed ice with natural peach puree and mint.",
        ingredients: ["Black Tea", "Peach Puree", "Mint", "Lemon Juice", "Ice"],
        isVeg: true,
        isVegan: true,
        isEggless: true,
        badge: "New",
        image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "cb5",
        name: "Real Strawberry Shake",
        category: "Cold Beverages",
        price: 120,
        rating: 4.7,
        reviewsCount: 220,
        description: "Luscious shake made with fresh Mahabaleshwar strawberries and rich vanilla cream.",
        ingredients: ["Fresh Strawberries", "Vanilla Ice Cream", "Whole Milk", "Strawberry Drizzle"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1472555794301-77455e1b5b3b?auto=format&fit=crop&w=600&q=80"
    },

    // SNACKS
    {
        id: "s1",
        name: "Crispy Potato Samosa (2 pcs)",
        category: "Snacks",
        price: 25,
        rating: 4.9,
        reviewsCount: 810,
        description: "Golden fried crust stuffed with spiced mashed potatoes, green peas, and fresh mint chutney.",
        ingredients: ["Potatoes", "Green Peas", "Spices", "Wheat Flour", "Mint Chutney"],
        isVeg: true,
        isVegan: true,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "s2",
        name: "Baked Veg Puff",
        category: "Snacks",
        price: 30,
        rating: 4.7,
        reviewsCount: 340,
        description: "Multi-layered buttery flaky pastry filled with curried veggies and aromatic spices.",
        ingredients: ["Puff Pastry", "Carrots", "Peas", "Corn", "Garam Masala"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "s3",
        name: "Peri Peri French Fries",
        category: "Snacks",
        price: 70,
        rating: 4.8,
        reviewsCount: 420,
        description: "Hand-cut crispy golden fries tossed in zesty African Peri Peri spice mix.",
        ingredients: ["Potatoes", "Peri Peri Seasoning", "Vegetable Oil", "Dip"],
        isVeg: true,
        isVegan: true,
        isEggless: true,
        badge: "Spicy",
        image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "s4",
        name: "Garlic Chilli Cheese Toast",
        category: "Snacks",
        price: 75,
        rating: 4.8,
        reviewsCount: 260,
        description: "Thick slice of artisan bread topped with roasted garlic butter, green chillies, and melted mozzarella.",
        ingredients: ["Artisan Bread", "Roasted Garlic", "Green Chillies", "Mozzarella Cheese", "Herbs"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=600&q=80"
    },

    // SANDWICHES
    {
        id: "sw1",
        name: "Bombay Veg Grill Sandwich",
        category: "Sandwiches",
        price: 80,
        rating: 4.9,
        reviewsCount: 590,
        description: "Triple layered sandwich with sliced beetroot, potato, cucumber, tomato, green chutney, and chat masala.",
        ingredients: ["Brown Bread", "Green Chutney", "Potato", "Beetroot", "Cucumber", "Butter"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "sw2",
        name: "Paneer Tikka Grilled Sandwich",
        category: "Sandwiches",
        price: 110,
        rating: 4.8,
        reviewsCount: 380,
        description: "Smoky tandoori paneer cubes stuffed with bell peppers, onions, and mint mayo in toasted sourdough.",
        ingredients: ["Paneer", "Tandoori Spices", "Bell Peppers", "Mint Mayo", "Multigrain Bread"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "sw3",
        name: "Spinach Corn Cheese Toastie",
        category: "Sandwiches",
        price: 95,
        rating: 4.7,
        reviewsCount: 210,
        description: "Sautéed fresh baby spinach and sweet corn smothered in creamy cheese sauce.",
        ingredients: ["Spinach", "Sweet Corn", "Cheddar Cheese", "White Bread", "Herbs"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1619860860774-1e2e17341d32?auto=format&fit=crop&w=600&q=80"
    },

    // BURGERS
    {
        id: "b1",
        name: "Classic Veg Crunch Burger",
        category: "Burgers",
        price: 100,
        rating: 4.7,
        reviewsCount: 460,
        description: "Crispy vegetable patty with fresh lettuce, juicy tomatoes, onions, and house secret sauce.",
        ingredients: ["Veg Patty", "Sesame Bun", "Lettuce", "Tomato", "House Sauce"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "b2",
        name: "Double Cheese Loaded Burger",
        category: "Burgers",
        price: 130,
        rating: 4.9,
        reviewsCount: 510,
        description: "Dual melted cheddar cheese slices melted over crunchy herb patty with caramelised onions.",
        ingredients: ["Herb Patty", "Cheddar Cheese", "Caramelized Onion", "Pickles", "Brioche Bun"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "b3",
        name: "Spicy Tandoori Paneer Burger",
        category: "Burgers",
        price: 150,
        rating: 4.8,
        reviewsCount: 390,
        description: "Whole char-grilled spicy paneer steak with tandoori mayo, jalapenos, and crisp iceberg lettuce.",
        ingredients: ["Paneer Steak", "Tandoori Sauce", "Jalapenos", "Iceberg Lettuce", "Toasted Bun"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Spicy",
        image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80"
    },

    // DESSERTS
    {
        id: "d1",
        name: "Sizzling Walnut Brownie",
        category: "Desserts",
        price: 80,
        rating: 4.9,
        reviewsCount: 710,
        description: "Fudgy dark chocolate walnut brownie served warm with a drizzle of hot chocolate fudge.",
        ingredients: ["Dark Chocolate", "Walnuts", "Cocoa Powder", "Butter", "Vanilla"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "d2",
        name: "Glazed Chocolate Donut",
        category: "Desserts",
        price: 60,
        rating: 4.7,
        reviewsCount: 230,
        description: "Soft fluffy fried ring donut topped with rich dark chocolate glaze and colorful sprinkles.",
        ingredients: ["Wheat Flour", "Dark Chocolate Glaze", "Rainbow Sprinkles", "Sugar"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "d3",
        name: "Choco Chip Muffin",
        category: "Desserts",
        price: 60,
        rating: 4.6,
        reviewsCount: 190,
        description: "Moist bakery muffin loaded generously with semi-sweet chocolate chips.",
        ingredients: ["Flour", "Semi-sweet Chocolate Chips", "Butter", "Milk"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "d4",
        name: "Belgian Chocolate Scoop Sundae",
        category: "Desserts",
        price: 70,
        rating: 4.8,
        reviewsCount: 310,
        description: "Two rich scoops of gourmet ice cream topped with roasted nuts and hot fudge.",
        ingredients: ["Milk", "Cream", "Cocoa", "Almonds", "Cashews"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80"
    },

    // CAKES
    {
        id: "ck1",
        name: "Dutch Truffle Chocolate Cake Slice",
        category: "Cakes",
        price: 90,
        rating: 4.9,
        reviewsCount: 680,
        description: "Decadent slice of moist sponge cake layered with rich dark chocolate truffle ganache.",
        ingredients: ["Cocoa Sponge", "Dark Chocolate Truffle", "Cream", "Choco Shavings"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Bestseller",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "ck2",
        name: "Red Velvet Cream Cheese Cake Slice",
        category: "Cakes",
        price: 110,
        rating: 4.8,
        reviewsCount: 430,
        description: "Vibrant crimson red velvet sponge cake layered with smooth vanilla bean cream cheese frost.",
        ingredients: ["Red Velvet Sponge", "Cream Cheese", "Buttercream", "Vanilla Extract"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Recommended",
        image: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "ck3",
        name: "New York Baked Cheesecake Slice",
        category: "Cakes",
        price: 130,
        rating: 4.9,
        reviewsCount: 350,
        description: "Classic smooth dense cheesecake on a crunchy graham cracker crust with berry compote.",
        ingredients: ["Cream Cheese", "Graham Cracker Crust", "Blueberry Compote"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "Popular",
        image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=600&q=80"
    },
    {
        id: "ck4",
        name: "Fresh Blueberry Pastry",
        category: "Cakes",
        price: 95,
        rating: 4.7,
        reviewsCount: 220,
        description: "Soft vanilla sponge layered with whipped cream and wild blueberry fruit filling.",
        ingredients: ["Vanilla Sponge", "Whipped Cream", "Wild Blueberry Filling"],
        isVeg: true,
        isVegan: false,
        isEggless: true,
        badge: "New",
        image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=600&q=80"
    }
];

// Combo Offers preset data
const COMBOS = [
    {
        id: "combo1",
        title: "Tea Time Combo",
        itemsText: "Masala Tea + Crispy Potato Samosa + Cookies",
        price: 79,
        originalPrice: 95,
        discountText: "Save ₹16",
        badge: "Best Seller Combo",
        image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80",
        itemsToCart: [
            { id: "t2", name: "Special Masala Tea", price: 30, image: "https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=600&q=80" },
            { id: "s1", name: "Crispy Potato Samosa (2 pcs)", price: 25, image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80" }
        ]
    },
    {
        id: "combo2",
        title: "Coffee Break Combo",
        itemsText: "Classic Cappuccino + Bombay Veg Grill Sandwich",
        price: 149,
        originalPrice: 160,
        discountText: "Save ₹11",
        badge: "Popular Combo",
        image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80",
        itemsToCart: [
            { id: "c2", name: "Classic Cappuccino", price: 80, image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=600&q=80" },
            { id: "sw1", name: "Bombay Veg Grill Sandwich", price: 80, image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80" }
        ]
    },
    {
        id: "combo3",
        title: "Weekend Sweet Feast",
        itemsText: "Dutch Truffle Cake Slice + Signature Iced Cold Coffee",
        price: 169,
        originalPrice: 190,
        discountText: "Flat 20% OFF",
        badge: "Weekend Special",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
        itemsToCart: [
            { id: "ck1", name: "Dutch Truffle Chocolate Cake Slice", price: 90, image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80" },
            { id: "cb1", name: "Signature Iced Cold Coffee", price: 100, image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=600&q=80" }
        ]
    }
];

// Customer Reviews sample data
const REVIEWS = [
    {
        id: "r1",
        name: "Aarav Sharma",
        role: "Regular Customer",
        rating: 5,
        comment: "The South Indian Filter Coffee and Samosas are unbelievable! Ban Ban is my go-to spot every afternoon.",
        avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80"
    },
    {
        id: "r2",
        name: "Priya Patel",
        role: "Food Blogger",
        rating: 5,
        comment: "Outstanding food quality, quick delivery, and the Dutch Truffle cake slice is divine! Highly recommend the online ordering experience.",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80"
    },
    {
        id: "r3",
        name: "Rohan Verma",
        role: "Tech Professional",
        rating: 5,
        comment: "The online ordering is smooth as butter. Cart updates instantly, and live order tracking kept me updated till my coffee arrived hot!",
        avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80"
    },
    {
        id: "r4",
        name: "Ananya Roy",
        role: "Dessert Enthusiast",
        rating: 5,
        comment: "Best Cappuccino and Paneer Burger in town! Love the warm ambiance when visiting and super speedy delivery when ordering home.",
        avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80"
    }
];
